#!/usr/bin/env php
<?php
require_once realpath(__DIR__ . "/../../autoload.php");

$consoleApp = \Parable\DI\Container::get(\Parable\Framework\ConsoleApp::class);
$consoleApp->setErrorReportingEnabled(true);
$consoleApp->run();
