#!/usr/bin/env php
<?php
ini_set('display_errors', '1');

/** @var \Parable\Console\App $app */
$app = require_once(__DIR__ . '/Framework/Bootstrap.php');

$command = new \Parable\Console\Command();

$app->setName('Parable');

/*
 * Set up some dependencies
 */
/** @var \Parable\Filesystem\Path $path */
$path = \Parable\DI\Container::get(\Parable\Filesystem\Path::class);
$path->setBasedir(BASEDIR);

$command->setName('init');
$command->setDescription('This command initializes a parable structure.');
$command->setCallable(function(
    \Parable\Console\Output $output,
    \Parable\Console\Input $input,
    \Parable\Console\Parameter $parameter
) use (
    $path
) {
    $output->writeln([
        "Parable initialization script",
        "-----------------------------------",
        "This script will initialize Parable's structure.",
        "",
    ]);

    for (;;) {
        $output->write("Do you want to continue? [y/N] ");
        if ($input->getYesNo(false)) {
            break;
        } else {
            $output->writeln(["", "<red>You chose not to continue.</red>", ""]);
            return;
        }
    }

    /** @var \Parable\Filesystem\Path $path */
    $output->newline();
    $output->write('Creating folder structure...');

    $dirs = [
        'app',
        'app/Config',
        'app/Controller',
        'app/Init',
        'app/Model',
        'app/Routes',
        'app/View',
        'app/View/Home',
        'public',
    ];

    foreach ($dirs as $dir) {
        if (!file_exists($path->getDir($dir))) {
            mkdir($path->getDir($dir));
        }
    }

    $output->writeln("<green>OK</green>");

    $output->write('Copying files...');
    copy(
        $path->getDir('vendor/devvoh/parable/structure/.htaccess'),
        $path->getDir('.htaccess')
    );
    copy(
        $path->getDir('vendor/devvoh/parable/structure/public/.htaccess'),
        $path->getDir('public/.htaccess')
    );
    copy(
        $path->getDir('vendor/devvoh/parable/structure/public/index.php'),
        $path->getDir('public/index.php')
    );
    copy(
        $path->getDir('vendor/devvoh/parable/structure/app/Routes/App.php'),
        $path->getDir('app/Routes/App.php')
    );
    copy(
        $path->getDir('vendor/devvoh/parable/structure/app/Config/App.php'),
        $path->getDir('app/Config/App.php')
    );
    copy(
        $path->getDir('vendor/devvoh/parable/structure/app/Controller/Home.php'),
        $path->getDir('app/Controller/Home.php')
    );
    copy(
        $path->getDir('vendor/devvoh/parable/structure/app/Init/Example.php'),
        $path->getDir('app/Init/Example.php')
    );
    copy(
        $path->getDir('vendor/devvoh/parable/structure/app/Model/User.php'),
        $path->getDir('app/Model/User.php')
    );
    copy(
        $path->getDir('vendor/devvoh/parable/structure/app/View/Home/index.phtml'),
        $path->getDir('app/View/Home/index.phtml')
    );

    $output->writeln("<green>OK</green>");

    $output->writeln(["", "<green>Completed!</green>", ""]);
});

$app->addCommand($command);

$app->run();