<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

        <title>Hello from Fluid PHP Framework</title>

        <!-- Open Sans font from google fonts -->
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,700,400italic,700italic' rel='stylesheet' type='text/css'>

        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

        <style>
            html {
                font-size: 16px;
            }
            * {
                font-family: 'Open Sans';
                font-weight: 400;
            }
            strong {
                font-weight: 700;
            }
            a {
                color: #196991;
                text-decoration: none;
            }
            a:hover {
                color: #239edb;
                text-decoration: underline;
            }
            .cover {
                position: fixed;
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                background: #ccc;
            }
            .container {
                position: absolute;
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                width: 500px;
                max-width: 90%;
                height: 300px;
                margin: auto;
            }
            .container-header {
                color: #239edb;
                padding-left: 0.75rem;
                font-weight: 700;
                font-size: 1.6rem;
            }
            .container-box {
                color: #444;
                padding: 0.75rem;
                margin: 0.5rem 0;
                background: #fff;
                border-top: 4px solid #239edb;
            }
            .container-footer {
                color: #444;
                font-size: 0.8rem;
                margin: 0;
                padding-right: 0.75rem;
                text-align: right;
            }
            .code {
                font-family: monospace;
                background: #ddd;
                font-size: 1rem;
            }
        </style>
    </head>
    <body>

        <section class="cover">

            <article class="container">
                <header class="container-header">
                    Fluid PHP Framework <?=$this->getVersion();?>
                </header>
                <p class="container-box">
                    If you see this, Fluid is working properly. You should now be able to start
                    building your application.
                    <br /><br />
                    This page is a controller/view combination. Check
                    <span class="code">app/modules/app/controller/home.php</span> and
                    <span class="code">app/modules/app/view/home/index.phtml</span>.
                    <br /><br />
                    If you need assistance, you can reach devvoh at our
                    <a href="https://github.com/devvoh/Fluid/">Github project page</a>.
                </p>
                <footer class="container-footer">
                    Fluid is a <a href="http://devvoh.com">devvoh project</a>, 2014-2015
                </footer>
            </article>

        </section>

    </body>
</html>
