<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

        <title>Hello from Fluid PHP Framework <?=self::getVersion();?></title>

        <!-- Raleway font from google fonts -->
        <link href='https://fonts.googleapis.com/css?family=Raleway:100' rel='stylesheet' type='text/css'>

        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

        <style>
            * {
                font-family: 'Raleway', sans-serif;
                font-weight: 100;
            }
            .container {
                position: absolute;
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                margin: auto;
                width: 100%;
                height: 4rem;
                line-height: 4rem;

                font-size: 4rem;
                text-align: center;
                color: #451eda;
            }
        </style>
    </head>
    <body>

        <section class="cover">

            <article class="container">
                Fluid <?=self::getVersion();?>
            </article>

        </section>

    </body>
</html>
