<?php /** @var $this \Devvoh\Parable\View */ ?>
<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

        <title>Hello from Parable PHP Framework <?=$this->tool->getVersion();?></title>

        <!-- Raleway font from google fonts -->
        <link href='https://fonts.googleapis.com/css?family=Raleway:100,400' rel='stylesheet' type='text/css'>

        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />

        <link rel="icon" type="image/png" href="./images/icon-32.png" />

        <style>
            * {
                font-family: 'Raleway', sans-serif;
                font-weight: 400;
            }
            .container {
                position: absolute;
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                margin: auto;
                width: 100%;
                height: 4rem;
                line-height: 4rem;

                text-align: center;
                color: #451eda;

                animation: fade-in 2s forwards;
            }
            a {
                color: #7e5deb;
                text-decoration: none;
            }
            a:hover {
                text-decoration: underline;
            }
            .container header {
                font-weight: 100;
                font-size: 4rem;
            }
            .container aside {
                font-size: 0.82rem;
                margin-top: -1.3rem;
                letter-spacing: 3px;
                margin-left: 3px;
            }
            @keyframes fade-in {
                from {opacity: 0;}
                to   {opacity: 1;}
            }
        </style>
    </head>
    <body>

        <section class="cover">

            <article class="container">
                <header>
                    Parable <?=$this->tool->getVersion();?>
                </header>
                <aside>
                    PHP framework by <a href="http://devvoh.com">devvoh</a>
                    -
                    <a href="https://github.com/devvoh/parable">github page</a>
                </aside>
            </article>

        </section>

    </body>
</html>
